#!/bin/bash

# Install Don Melton's Video Transcoding Gem
# https://github.com/donmelton/video_transcoding
sudo gem install video_transcoding

# Adjust defaults

###############################################################################
# Power Options - Desktop                                                     #
###############################################################################

# Change default sleep from 0 to 60 minutes
sudo pmset -a sleep 60

# Irrelevant with an SSD, but pmset is an asshole about sleep settings.
sudo pmset -a disksleep 60

# Turn on powernap
sudo pmset -a powernap 1

# Set bounds for standby -> hibernate
sudo pmset -a standbydelayhigh 86400
sudo pmset -a standbydelaylow 86400
sudo pmset -a standbydelay 86400

# Turn off hibernate
sudo pmset -a hibernatemode 0

# Turn off standby
sudo pmset -a standby 0

# Disable autopoweroff to off
sudo pmset -a autopoweroff 0
sudo pmset -a autopoweroffdelay 86400

# Dim display off
sudo pmset -a lessbright 0

# Set display sleep
sudo pmset -a displaysleep 60

###############################################################################
# Screen Saver                                                                #
###############################################################################

# Screen Saver: Aerial
defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName -string "Aerial" path -string "/Library/Screen Savers/Aerial.saver" type -int 0
