#!/bin/bash

# Install Don Melton's Video Transcoding Gem
# https://github.com/donmelton/video_transcoding
sudo gem install video_transcoding

# Install pip for python goodness
sudo easy_install pip

#slack cleaner
sudo pip install slack-cleaner

sudo mv $HOME/Desktop/archey /usr/local/bin/archey
mv "$HOME/Desktop/inAudible.app" /Applications

# Download some apps
dirAppHome=$HOME/Desktop
wget -O "$dirAppHome/Duplicate Annihilator for Photos.dmg.zip" https://brattoo.com/propaganda/downloadDap.php
wget -O "$dirAppHome/photosSetLongitudeAndLatitude.zip" https://free.brattoo.com/apps/photosSetLongitudeAndLatitude.zip
wget -O "$dirAppHome/photodateToFiledate.zip" https://free.brattoo.com/apps/photodateToFiledate.zip
wget -O "$dirAppHome/MP3 Trimmer.dmg" http://deepniner.net/mp3trimmer/MP3%20Trimmer.dmg
unzip -qq "$dirAppHome/Duplicate Annihilator for Photos.dmg.zip" -d $dirAppHome ;rm -rf $dirAppHome/__MACOSX
unzip -qq "$dirAppHome/photosSetLongitudeAndLatitude.zip" -d $dirAppHome ;rm -rf $dirAppHome/__MACOSX
unzip -qq "$dirAppHome/photodateToFiledate.zip" -d $dirAppHome ;rm -rf $dirAppHome/__MACOSX

hdiutil attach -nobrowse "$HOME/Desktop/Duplicate Annihilator for Photos.dmg"
cp -r "/Volumes/Duplicate Annihilator for Photos/Duplicate Annihilator for Photos.app" /Applications
hdiutil detach "/Volumes/Duplicate Annihilator for Photos"

hdiutil attach -nobrowse "$HOME/Desktop/MP3 Trimmer.dmg"
cp -r "/Volumes/MP3 Trimmer/MP3 Trimmer.app" /Applications
hdiutil detach "/Volumes/MP3 Trimmer"

mv "$dirAppHome/Photos Set longitude and latitude.app" /Applications
mv "$dirAppHome/Photodate to Filedate.app" /Applications
rm "$HOME/Desktop/Duplicate Annihilator for Photos.dmg"
rm "$HOME/Desktop/MP3 Trimmer.dmg"
rm "$dirAppHome/Duplicate Annihilator for Photos.dmg.zip"
rm "$dirAppHome/photosSetLongitudeAndLatitude.zip"
rm "$dirAppHome/photodateToFiledate.zip"

###############################################################################
# Power Options                                                               #
###############################################################################

source "$BOOTSTRAP_DIR/custom/power_settings_desktop.sh"

###############################################################################
# Screen Saver                                                                #
###############################################################################

# Screen Saver: Aerial
defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName -string "Aerial" path -string "$HOME/Library/Screen Savers/Aerial.saver" type -int 0

###############################################################################
# Add launchctl jobs.                                                         #
###############################################################################

mv "$BOOTSTRAP_DIR/custom/com.khaosx.dailywork_lithium.plist" "$HOME/Library/LaunchAgents/com.khaosx.dailywork.plist"
launchctl load ~/Library/LaunchAgents/com.khaosx.dailywork.plist