#!/bin/bash

# Install Don Melton's Video Transcoding Gem
# https://github.com/donmelton/video_transcoding
sudo gem install video_transcoding

# Adjust defaults

###############################################################################
# Screen Saver                                                                #
###############################################################################

# Screen Saver: Aerial
defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName -string "Aerial" path -string "/System/Library/Screen Savers/Aerial.saver" type -int 0