#!/bin/bash

# Adjust defaults

###############################################################################
# Power Options                                                               #
###############################################################################

# Change default sleep from 0 to 60 
sudo pmset -a sleep 60

# Irrelevant with an SSD, but pmset is an asshole about sleep settings.
sudo pmset -a disksleep 60

###############################################################################
# Extras
###############################################################################

# Activate audible chime when power cable is plugged in.
defaults write com.apple.PowerChime ChimeOnAllHardware -bool true; open /System/Library/CoreServices/PowerChime.app
