#!/bin/bash

# Adjust defaults

###############################################################################
# Power Options                                                               #
###############################################################################

source "$BOOTSTRAP_DIR/custom/power/power_settings_laptop.sh"