#!/bin/bash

# Add Users
function create_reg_users () {
	LastID=`dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1`
	NextID=$((LastID + 1))
	sudo dscl . -create /Users/$1
	sudo dscl . -create /Users/$1 UserShell /bin/bash
	sudo dscl . -create /Users/$1 RealName "$2"
	sudo dscl . -create /Users/$1 UniqueID $NextID
	sudo dscl . -create /Users/$1 PrimaryGroupID 20
	sudo dscl . -create /Users/$1 NFSHomeDirectory /Users/$1
	sudo dscl . -passwd /Users/$1 $1
	sudo createhomedir -c -u $1
	FILE=$HOME/Desktop/Sodium/ParentalControls/$1.parentalcontrols
	if [ -f $FILE ]; then
		echo Restoring parental controls for $1
		sudo dscl . -mcximport /Users/$1 $HOME/Desktop/Sodium/ParentalControls/$1.parentalcontrols
	else
		echo Individual parental controls for $1 not available. Installing generic controls
		sudo dscl . -mcximport /Users/$1 $HOME/Desktop/Sodium/ParentalControls/generic.parentalcontrols
	fi
}

function create_admin_users () {
	LastID=`dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1`
	NextID=$((LastID + 1))
	sudo dscl . -create /Users/$1
	sudo dscl . -create /Users/$1 UserShell /bin/bash
	sudo dscl . -create /Users/$1 RealName "$2"
	sudo dscl . -create /Users/$1 UniqueID $NextID
	sudo dscl . -create /Users/$1 PrimaryGroupID 20
	sudo dscl . -create /Users/$1 NFSHomeDirectory /Users/$1
	sudo dscl . -passwd /Users/$1 $1
	sudo createhomedir -c -u $1
	sudo dscl . -append /Groups/admin GroupMembership $1
	sudo pwpolicy -a kris -u $1 -setpolicy "newPasswordRequired=1"
}

# Adjust defaults

###############################################################################
# Power Options                                                               #
###############################################################################

source "$BOOTSTRAP_DIR/custom/power_settings_desktop.sh"

###############################################################################
# Create Users                                                                #
###############################################################################

create_reg_users "caleb" "Caleb Abbott"
create_reg_users "harper" "Harper Abbott"
create_reg_users "shelby" "Shelby Newman"
create_admin_users "sara" "Sara Newman"

osascript -e 'tell app "loginwindow" to «event aevtrrst»'
