#!/bin/bash

# Add Users
function create_reg_users () {
	LastID=`dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1`
	NextID=$((LastID + 1))
	sudo dscl . -create /Users/$1
	sudo dscl . -create /Users/$1 UserShell /bin/bash
	sudo dscl . -create /Users/$1 RealName "$2"
	sudo dscl . -create /Users/$1 UniqueID $NextID
	sudo dscl . -create /Users/$1 PrimaryGroupID 20
	sudo dscl . -create /Users/$1 NFSHomeDirectory /Users/$1
	sudo dscl . -passwd /Users/$1 $1
	sudo createhomedir -c -u $1
	FILE=$HOME/Desktop/Sodium/ParentalControls/$1.parentalcontrols
	if [ -f $FILE ]; then
		echo Restoring parental controls for $1
		sudo dscl . -mcximport /Users/$1 $HOME/Desktop/Sodium/ParentalControls/$1.parentalcontrols
	else
		echo Individual parental controls for $1 not available. Installing generic controls
		sudo dscl . -mcximport /Users/$1 $HOME/Desktop/Sodium/ParentalControls/generic.parentalcontrols
	fi
}

function create_admin_users () {
	LastID=`dscl . -list /Users UniqueID | awk '{print $2}' | sort -n | tail -1`
	NextID=$((LastID + 1))
	sudo dscl . -create /Users/$1
	sudo dscl . -create /Users/$1 UserShell /bin/bash
	sudo dscl . -create /Users/$1 RealName "$2"
	sudo dscl . -create /Users/$1 UniqueID $NextID
	sudo dscl . -create /Users/$1 PrimaryGroupID 20
	sudo dscl . -create /Users/$1 NFSHomeDirectory /Users/$1
	sudo dscl . -passwd /Users/$1 $1
	sudo createhomedir -c -u $1
	sudo dscl . -append /Groups/admin GroupMembership $1
	sudo pwpolicy -a kris -u $1 -setpolicy "newPasswordRequired=1"
}

# Adjust defaults

###############################################################################
# Power Options - Desktop                                                     #
###############################################################################

# Change default sleep from 0 to 60 minutes
sudo pmset -a sleep 60

# Irrelevant with an SSD, but pmset is an asshole about sleep settings.
sudo pmset -a disksleep 60

# Set display sleep
sudo pmset -a displaysleep 60

# Turn on powernap
sudo pmset -a powernap 1

# Set bounds for standby -> hibernate
sudo pmset -a standbydelayhigh 86400
sudo pmset -a standbydelaylow 86400
sudo pmset -a standbydelay 86400

# Turn off hibernate
sudo pmset -a hibernatemode 0

# Turn off standby
sudo pmset -a standby 0

# Disable autopoweroff to off
sudo pmset -a autopoweroff 0
sudo pmset -a autopoweroffdelay 86400

# Dim display off
sudo pmset -a lessbright 0

###############################################################################
# Create Users                                                                #
###############################################################################

create_reg_users "caleb" "Caleb Abbott"
create_reg_users "harper" "Harper Abbott"
create_reg_users "shelby" "Shelby Newman"
create_admin_users "sara" "Sara Newman"

osascript -e 'tell app "loginwindow" to «event aevtrrst»'
