#!/bin/bash

dockutil --no-restart --remove all

dockutil --no-restart --add "/Applications/Safari.app"
dockutil --no-restart --add "/Applications/Google Chrome.app"
dockutil --no-restart --add "/Applications/Mail.app"
dockutil --no-restart --add "/Applications/Messages.app"
dockutil --no-restart --add "/Applications/News.app"
dockutil --no-restart --add "/Applications/Calendar.app"
dockutil --no-restart --add "/Applications/Contacts.app"
dockutil --no-restart --add "/Applications/Notes.app"
dockutil --no-restart --add "/Applications/Reminders.app"
dockutil --no-restart --add "/Applications/Maps.app"
dockutil --no-restart --add "/Applications/iTunes.app"
dockutil --no-restart --add "/Applications/Photos.app"
dockutil --no-restart --add "/Applications/TextWrangler.app"
dockutil --no-restart --add "/Applications/BBEdit.app" 
dockutil --no-restart --add "/Applications/MakeMKV.app"
dockutil --no-restart --add "/Applications/Transmit.app"
dockutil --no-restart --add "/Applications/Reeder.app"
dockutil --no-restart --add "/Applications/FileBot.app"
dockutil --no-restart --add "/Applications/Numbers.app"
dockutil --no-restart --add "/Applications/Pages.app"
dockutil --no-restart --add "/Applications/Paprika Recipe Manager 3.app"
dockutil --no-restart --add "/Applications/Plex Media Player.app"
dockutil --no-restart --add "/Applications/ScanSnap/ScanSnap Manager.app"
dockutil --no-restart --add "/Applications/Sonos.app"
dockutil --no-restart --add "/Applications/Utilities/Terminal.app"
dockutil --no-restart --add "/Applications/App Store.app"
dockutil --no-restart --add "/Applications/System Preferences.app"
dockutil --no-restart --add "~/Downloads" --view fan --section others --sort dateadded --display folder

if [ "$HOST_NAME" = magnesium ]; then
    dockutil --no-restart --remove "Google Chrome"
    dockutil --no-restart --remove "ScanSnap Manager"
    dockutil --no-restart --remove "Transmit"
    dockutil --no-restart --remove "Sonos"
    dockutil --no-restart --remove "MakeMKV"
elif [ "$HOST_NAME" = sodium ]; then
    dockutil --no-restart --remove "Google Chrome"
    dockutil --no-restart --remove "ScanSnap Manager"
    dockutil --no-restart --remove "Transmit"
    dockutil --no-restart --remove "MakeMKV"
    dockutil --no-restart --remove "Filebot"
    dockutil --no-restart --remove "Plex Media Player"
    dockutil --no-restart --remove "Reeder"
elif [ "$HOST_NAME" = lithium ]; then
    dockutil --no-restart --remove "TextWrangler"
fi

killall Dock
