#!/bin/bash

dockutil --no-restart --remove all

dockutil --no-restart --add "/Applications/Safari.app"
dockutil --no-restart --add "/Applications/Google Chrome.app"
dockutil --no-restart --add "/Applications/Mail.app"
dockutil --no-restart --add "/Applications/Messages.app"
dockutil --no-restart --add "/Applications/Calendar.app"
dockutil --no-restart --add "/Applications/Contacts.app"
dockutil --no-restart --add "/Applications/Notes.app"
dockutil --no-restart --add "/Applications/Reminders.app"
dockutil --no-restart --add "/Applications/Maps.app"
dockutil --no-restart --add "/Applications/iTunes.app"
dockutil --no-restart --add "/Applications/Photos.app"
dockutil --no-restart --add "/Applications/TextWrangler.app"
dockutil --no-restart --add "/Applications/Reeder.app"
dockutil --no-restart --add "/Applications/FileBot.app"
dockutil --no-restart --add "/Applications/Numbers.app"
dockutil --no-restart --add "/Applications/Pages.app"
dockutil --no-restart --add "/Applications/Paprika Recipe Manager 3.app"
dockutil --no-restart --add "/Applications/Plex Media Player.app"
dockutil --no-restart --add "/Applications/ScanSnap/ScanSnap Manager.app"
dockutil --no-restart --add "/Applications/Sonos.app"
dockutil --no-restart --add "/Applications/Utilities/Terminal.app"
dockutil --no-restart --add "/Applications/App Store.app"
dockutil --no-restart --add "/Applications/System Preferences.app"
dockutil --no-restart --add "~/Downloads" --view fan --section others --sort dateadded --display folder
killall Dock

# If you have trouble with icons appearing as generic placeholders, try running
# the following commands.

# sudo rm -rfv /Library/Caches/com.apple.iconservices.store
# sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \;
# sleep 3;
# sudo touch /Applications/*
# killall Dock
# killall Finder

# Reference:
# - https://gist.github.com/fabiofl/5873100
# - https://www.hackintosh.blog/article/24/rebuild-icon-cache-macos/
